### ISSUE TITLE
Make it possible to use graphiql without CDN

### ISSUE THREAD

**Issue by mike-marcacci** [apollographql/graphql-server#376] opened 2017-04-29 04:46 UTC
This is basically identical to [this old issue over at the official graphiql repo](https://github.com/graphql/graphiql/issues/135): graphiql needs to work in offline/intranet/sandboxed/whatever environments.

I'm currently in a mostly offline scenario (dial-up quality cell service) and the dependency on jsdelivr.net was definitely something I didn't anticipate when getting everything ready for offline work.

**Comment by helfer** [comment] 2017-04-29 06:43
Hi @mike-marcacci! :wave: I totally agree, this is a duplicate of #295 I think. A PR would be very much appreciated!

**Closed by helfer** 2017-04-29 06:43 UTC

**Comment by mike-marcacci** [comment] 2017-04-29 19:50
Agreed! Sorry I missed that one (was quite bandwidth-limited while searching existing issues). I'll see if I can get a moment to help w/ a PR. Just wanted to make sure it was recorded somewhere!
