### ISSUE TITLE
UnhandledPromiseRejectionWarning for errors that is not HttpQueryError

### ISSUE THREAD

**Issue by Ramzeus** [apollographql/graphql-server#384] opened 2017-05-09 09:34 UTC
I came across a problem related to this line of code: https://github.com/apollographql/graphql-server/blob/master/packages/graphql-server-express/src/expressApollo.ts#L40

I got the problem when I tried to call a mutation and used the wrong data type for a mutation parameter object (Boolean instead of Date). I got no error response at all from the server, and in the server console I got this message:
`(node:6352) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): GraphQLError: Query error: Can only parse strings to dates but got a: BooleanValue
(node:6352) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Instead of being a HttpQueryError it was a GraphQLError and the error was just thrown without being caught anywhere.

The reason for the GraphQLError is because my date scalar type plugin checks to see if the supplied date string is a valid date or not (in parseLiteral). In this case it was not, so therefore it throws an error.

Maybe the type plugin should do something else, but it seems to me that apollo should take care of returning a proper error response to the client regardless.

**Comment by helfer** [comment] 2017-05-12 04:25
Hey @Ramzeus can you verify that this isn't an error that would be uncaught when you're just calling the `graphql` function in `graphql-js` directly? I suspect that this error is thrown in an uncatchable way in `graphql-js`. I know there was a recent change related to parseLiteral and parseValue in graphql-js.

**Comment by trotzig** [comment] 2017-05-16 12:09
I think this is a duplicate of #313. I'm going to try coming up with a PR that will at least surface the error better.

**Comment by helfer** [comment] 2017-06-28 21:32
Hey @trotzig, let us know if you want to PR that fix!

**Comment by trotzig** [comment] 2017-06-29 08:16
It's already been merged (in https://github.com/apollographql/graphql-server/pull/390) I believe.

**Comment by helfer** [comment] 2017-06-29 23:36
Ok great, in that case I'll close the issue!

**Closed by helfer** 2017-06-29 23:36 UTC
